global:
  scrape_interval: 60s  # 1-minute refresh cycles
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'pentameter'
    static_configs:
      - targets: ['pentameter-app:8080']
    scrape_interval: 60s
    metrics_path: /metrics